ci:
    skip: [black]

repos:
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      args:
        - --config=.flake8
-   repo: https://github.com/pycqa/pylint
    rev: v2.10.2
    hooks:
    - id: pylint
      args:
      - --rcfile=.pylintrc
      additional_dependencies:
        - pylint_pytest==1.1.2
-   repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
    - id: black
      language_version: python3
      args:
          - --config
          - pyproject_black.toml
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    -   id: bandit
        args:
          - -c
          - bandit.yaml
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'
    hooks:
    -   id: mypy
        args:
          - --config-file=mypy.ini
-   repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
    -   id: isort
        args:
          - --sp
          - .isort.cfg
