ci:
    skip: [black]

repos:
-   repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
      args:
        - --config=.flake8
-   repo: https://github.com/pycqa/pylint
    rev: v2.14.5
    hooks:
    - id: pylint
      args:
      - --rcfile=.pylintrc
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      language_version: python3
      args:
          - --config
          - pyproject_black.toml
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
        args:
          - -c
          - bandit.yaml
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.971'
    hooks:
    -   id: mypy
        args:
          - --config-file=mypy.ini
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args:
          - --sp
          - .isort.cfg
