codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    patch:                      # measuring the overall project coverage
      default:                  # context, you can create multiple ones with custom titles
        enabled: yes            # must be yes|true to enable this status
        target: 90%             # specify the target coverage for each commit status
                                #   option: "auto" (must increase from parent commit or pull request base)
                                #   option: "X%" a static target percentage to hit
        threshold: null         # allowed to drop X% and still result in a "success" commit status
        if_not_found: success   # if parent is not found report status as success, error, or failure
        if_ci_failed: error     # if ci fails report status as success, error, or failure

    project:
      default:
        enabled: yes            # must be yes|true to enable this status
        target: 90%             # specify the target coverage for each commit status
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "examples"